### ISSUE TITLE
bug: fails without explicitly setting a --ledger-file value

### ISSUE THREAD

**Issue by ajamian** [quentinsf/icsv2ledger#102]
Thank you for an excellent utility!

I started using about a year ago. A couple months ago I finally updated my local clone to your latest changes and found that the commands I had been using were failing. After some debug, it appears that the codeflow without a --ledger-file passed bypasses the only logic that initializes a couple of sets, without these initialized the code fails later.

Also noticed that the utility now assumes the ledger executable is in the current PATH.

I have a bugfix in my fork of the tool, as well as a small edit to the README stating that the ledger binary must be in the current shell PATH. Happy to open a pull request.

**Comment by petdr** [comment]
Thanks for the pr.
