### ISSUE TITLE
What is the correct .icsv2ledgerrc format

### ISSUE THREAD

**Issue by afduggirala** [quentinsf/icsv2ledger#120]
The point of the .icsv2ledgerrc file is that it is not necessary to specify its location or usage when executing ./icsv2ledger.py right?
And then the sole purpose of this file (.icsv2ledgerrc) is to specify the location of the configfile (configfile.txt) right?
Can anyone provide a sample .icsv2ledgerrc file for me to see? 
My .ics2ledgerrc file reads as follows:
config_file=/home/user/configs/configfile.txt

And I am getting this error when running ./icsv2ledgerrc without specifying a config file:
Traceback (most recent call last):
  File "./icsv2ledger.py", line 982, in <module>
    main()
  File "./icsv2ledger.py", line 797, in main
    options = parse_args_and_config_file()
  File "./icsv2ledger.py", line 206, in parse_args_and_config_file
    config.read(args.config_file)
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/anil/.icsv2ledgerrc', line: 1
'config_file=/home/anil/configs/configfile.txt\n'

thank you,

**Comment by TomAtGithub** [comment]
"File contains no section headers." means you are missing the [BANK] part at the beginning of your config. As described here: https://github.com/quentinsf/icsv2ledger#configuration-file-example

Then you must add the bank account as argument to icsv2ledger. Which is a bit confusing as account is also mentioned in the config file as the assets account.

`icsv2ledger -a BANK -c /home/user/configs/configfile.txt file.csv file.ledger`

**Comment by afduggirala** [comment]
That is right. At that time, I had misunderstood the use of the .icsv2ledgerrc file. I thought that file was meant for broader config options, such as specifying the path and name of the actual --config-file. Only later, I realized the .icsv2ledgerrc file IS the --config-file (and can be used automatically, without specifying it when executing icsv2ledger). So naturally, I was missing a lot of stuff in my .icsv2ledgerrc file.
thank you.
