### ISSUE TITLE
Support ( at the beginning of amount to signal a debit

### ISSUE THREAD

**Issue by mb-dev** [quentinsf/icsv2ledger#76]
My bank uses ($123.00) to mean debit $123. Currently only the - character is supported. As a result, I am getting positive amounts

**Comment by OliverCardoza** [comment]
Same problem. get_field_at_index needs an extra check to convert () to -
https://github.com/quentinsf/icsv2ledger/blob/master/icsv2ledger.py#L498

I'll take a look tomorrow
