### ISSUE TITLE
Account naming restriction in account file should be mentioned in documentation

### ISSUE THREAD

**Issue by msmart** [quentinsf/icsv2ledger#90]
I have a ledger with account names containing non-us characters such as ääüß, etc. (The ledger contains transaction data in German).

When invoking icsv2ledger with the option --accounts-file these account names are not accepted.

This is due to the regexp patter at https://github.com/quentinsf/icsv2ledger/blob/master/icsv2ledger.py#L623

I believe it could be helpful to mention this restriction at https://github.com/quentinsf/icsv2ledger/blob/master/README.md#accounts-file

or alternatively allow special characters in the regexp pattern.

**Comment by tikank** [comment]
As ledger supports non-ascii charaters in account names, I think icsv2ledger should also do so. I made pull request for the change, https://github.com/quentinsf/icsv2ledger/pull/91.
