### ISSUE TITLE
Do you want any of these features?

### ISSUE THREAD

**Issue by kalafut** [quentinsf/icsv2ledger#92]
Hi,

First: icsv2ledger is great. It is by far the most helpful addition to ledger for me.

I've been making some small additions that you might be interested in. If your are, let me know and I can structure a PR. I didn't want to just hit you with a PR since you may want some but not all changes, style might not be to your liking, etc.  Check out: https://github.com/kalafut/icsv2ledger/commits/master

In summary they are:

- --incremental mode. This changes the output behavior to both: a) append  b) output after every transaction. I like to watch and tweak the output in my editor as I go. This would also address #60 I think.
- --skip-dupes. Ignored "duplicates", which are currently defined as those CSV lines that already appear as a CSV: ... comments in the ledger file. This is a conservative approach vs MD5. I worry that if a bank changes anything (caps, quote style, spacing around commas), the MD5-style dupe detection would be hopelessly lost. At least with the full CSV line, one could improve the logic to detect "close enough" (e.g. only CSV formatting changes or whatever). This naturally relies on CSV: being in the template.
- Trim trailing whitespace on output. (Does anyone actually like trailing WS?)
- Allow ctrl-c without showing an ugly exception. I frequently exit and tweak the mapping file, then reload.

Running all of these together has really improved my workflow. I enter and exit the program frequently, adjust the output and mappings as I go, and with --skip-dupes I make constant forward progress.

**Comment by petdr** [comment]
These all sound very useful, please prepare a pull request and I will merge it in.

**Comment by kalafut** [comment]
Sounds good. I hope to get to it in the the next couple of weeks.
