### ISSUE TITLE
Only saves to ledger file when --incremental option is used

### ISSUE THREAD

**Issue by KevinCaseiras** [quentinsf/icsv2ledger#96]
After running the command:
`./icsv2ledger.py -c config.txt -a CHASE ChaseCredit.csv ledger.dat`
the `ledger.dat` file is empty unless I use the `--incremental` option.

The above command works on previous commits, which makes me believe it is a bug.

I will be submitting a PR with a fix if you are interested.
To fix this, my PR makes icsv2ledger always write to the ledger file incrementally. Therefore the only functionality of the `--incremental` flag is to append to the ledger file instead of overwriting. Let me know if you would prefer it be renamed to `--append`. I didn't want to break backwards compatibility. Consequently I fixed the incompatibility between the `--reverse` and `--incremental` options.

**Comment by themiurgo** [comment]
I'm also experiencing this issue.
